-- HighGAS: catálogo público e somente-leitura de localizações VPN.
-- Aplicar em um projeto Supabase NOVO e separado.
-- A chave privada e o conteúdo de perfis WireGuard NÃO devem ser gravados aqui.

create table if not exists public.highgas_servers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  country_code text not null check (char_length(country_code) = 2),
  country_name text not null,
  city text not null,
  protocol text not null default 'wireguard'
    check (protocol in ('wireguard', 'openvpn')),
  status text not null default 'online'
    check (status in ('online', 'maintenance', 'offline')),
  is_recommended boolean not null default false,
  enabled boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.highgas_servers enable row level security;

-- Supabase mudou os defaults de exposição da Data API em 2026.
-- O frontend precisa apenas de SELECT anônimo para este catálogo.
revoke all on table public.highgas_servers from anon, authenticated;
grant select on table public.highgas_servers to anon, authenticated;

drop policy if exists "highgas_public_read_enabled_servers"
  on public.highgas_servers;

create policy "highgas_public_read_enabled_servers"
on public.highgas_servers
for select
to anon, authenticated
using (enabled = true);

insert into public.highgas_servers
  (code, country_code, country_name, city, protocol, status, is_recommended, enabled, sort_order)
values
  ('br-sao-01', 'BR', 'Brasil', 'São Paulo', 'wireguard', 'online', true, true, 10),
  ('us-mia-01', 'US', 'Estados Unidos', 'Miami', 'wireguard', 'online', false, true, 20),
  ('nl-ams-01', 'NL', 'Países Baixos', 'Amsterdam', 'wireguard', 'online', false, true, 30),
  ('de-fra-01', 'DE', 'Alemanha', 'Frankfurt', 'wireguard', 'online', false, true, 40),
  ('gb-lon-01', 'GB', 'Reino Unido', 'Londres', 'wireguard', 'online', false, true, 50)
on conflict (code) do update set
  country_code = excluded.country_code,
  country_name = excluded.country_name,
  city = excluded.city,
  protocol = excluded.protocol,
  status = excluded.status,
  is_recommended = excluded.is_recommended,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order,
  updated_at = now();

comment on table public.highgas_servers is
  'Catálogo público de países/servidores do frontend HighGAS; nunca armazenar chaves privadas ou perfis WireGuard.';
