import { neon } from "@neondatabase/serverless";

const fallbackServers = [
  { id: 1, code: "br-sao-01", country_code: "BR", country_name: "Brasil", city: "São Paulo", protocol: "wireguard", status: "online", is_recommended: true, sort_order: 10 },
  { id: 2, code: "us-mia-01", country_code: "US", country_name: "Estados Unidos", city: "Miami", protocol: "wireguard", status: "online", is_recommended: false, sort_order: 20 },
  { id: 3, code: "nl-ams-01", country_code: "NL", country_name: "Países Baixos", city: "Amsterdam", protocol: "wireguard", status: "online", is_recommended: false, sort_order: 30 },
  { id: 4, code: "de-fra-01", country_code: "DE", country_name: "Alemanha", city: "Frankfurt", protocol: "wireguard", status: "online", is_recommended: false, sort_order: 40 },
  { id: 5, code: "gb-lon-01", country_code: "GB", country_name: "Reino Unido", city: "Londres", protocol: "wireguard", status: "online", is_recommended: false, sort_order: 50 },
];

const getSql = (databaseUrl) => neon(databaseUrl);

const queryCatalog = async (databaseUrl) => {
  const sql = getSql(databaseUrl);
  return sql`
    select
      id,
      code,
      country_code,
      country_name,
      city,
      protocol,
      status,
      is_recommended,
      sort_order
    from public.highgas_servers
    where is_active = true
      and status <> 'offline'
    order by sort_order asc, id asc
  `;
};

const ensureCatalog = async (databaseUrl) => {
  const sql = getSql(databaseUrl);

  await sql`
    create table if not exists public.highgas_servers (
      id bigint generated by default as identity primary key,
      code text not null unique,
      country_code text not null,
      country_name text not null,
      city text not null,
      protocol text not null default 'wireguard',
      status text not null default 'online',
      is_recommended boolean not null default false,
      is_active boolean not null default true,
      sort_order integer not null default 100,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    )
  `;

  await sql`
    insert into public.highgas_servers
      (code, country_code, country_name, city, protocol, status, is_recommended, is_active, sort_order)
    values
      ('br-sao-01', 'BR', 'Brasil', 'São Paulo', 'wireguard', 'online', true, true, 10),
      ('us-mia-01', 'US', 'Estados Unidos', 'Miami', 'wireguard', 'online', false, true, 20),
      ('nl-ams-01', 'NL', 'Países Baixos', 'Amsterdam', 'wireguard', 'online', false, true, 30),
      ('de-fra-01', 'DE', 'Alemanha', 'Frankfurt', 'wireguard', 'online', false, true, 40),
      ('gb-lon-01', 'GB', 'Reino Unido', 'Londres', 'wireguard', 'online', false, true, 50)
    on conflict (code) do update set
      country_code = excluded.country_code,
      country_name = excluded.country_name,
      city = excluded.city,
      protocol = excluded.protocol,
      status = excluded.status,
      is_recommended = excluded.is_recommended,
      is_active = excluded.is_active,
      sort_order = excluded.sort_order,
      updated_at = now()
  `;
};

const relationMissing = (error) =>
  error instanceof Error && /highgas_servers.*does not exist|relation .*highgas_servers.*does not exist/i.test(error.message);

export default async function handler(req, res) {
  if (req.method !== "GET") {
    res.setHeader("Allow", "GET");
    return res.status(405).json({ error: "Method not allowed" });
  }

  const connectionCandidates = [
    ["postgres", process.env.POSTGRES_URL],
    ["database", process.env.DATABASE_URL],
  ].filter(([, value], index, all) =>
    Boolean(value) && all.findIndex(([, candidate]) => candidate === value) === index
  );

  for (const [source, databaseUrl] of connectionCandidates) {
    try {
      let servers;

      try {
        servers = await queryCatalog(databaseUrl);
      } catch (error) {
        if (!relationMissing(error)) throw error;
        await ensureCatalog(databaseUrl);
        servers = await queryCatalog(databaseUrl);
      }

      if (Array.isArray(servers) && servers.length > 0) {
        res.setHeader("X-HighGAS-Source", "neon");
        res.setHeader("X-HighGAS-Connection", source);
        res.setHeader(
          "Cache-Control",
          "public, s-maxage=60, stale-while-revalidate=300"
        );
        return res.status(200).json(servers);
      }
    } catch (error) {
      console.error(
        `HighGAS Neon query failed (${source})`,
        error instanceof Error ? error.message : String(error)
      );
    }
  }

  res.setHeader("X-HighGAS-Source", "fallback");
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=60, stale-while-revalidate=300"
  );
  return res.status(200).json(fallbackServers);
}
